language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
install:
- pip install -r build_requirements.txt
- pip install -r requirements.txt
script:
- py.test -v --cov winrm --cov-report term-missing winrmlib/tests/
deploy:
  provider: pypi
  user: ianclegg
  password:
    secure: DeGDOeaXF9cX6WA8E6Vj93bMG3s88kbfmnWO/SYVnMhZS3rLn5vaeAVFEcPCyFoqivApj7q+c4ehoZvWafgAN4Gt5s96PhALIRwciUWD+haXUEEQcXbeQ1ihCqfBKyt5N77B8wDhmcqdAkkIIOWcuDW5s/xmUM5u201nT8qSwAE=
