# http://travis-ci.org/#!/ianclegg/winrmlib
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  # ensure build dependencies
  - pip install -r build_requirements.txt

  # ensure documentation dependencies
  #- pip install -r docs/requirements.txt --use-mirrors
  
  # ensure package dependencies
  - pip install -r requirements.txt
script:
  #TODO Run Unit Tests
  #py.test -v --pep8 winrm --cov winrm --cov-report term-missing winrmlib/tests/
  - py.test -v --cov winrm --cov-report term-missing winrmlib/tests/
after_success:
  - coveralls
  # Build a Source Distribution and Egg
  - pwd && cd src
  - python setup.py bdist_egg
  - python setup.py sdist
  - cd ..
  # Ensure the the distributions install and uninstall
  - pwd && cd src/dist
  - pip install winrmlib-*.tar.gz
  - echo "y" | pip uninstall winrmlib
  - easy_install winrmlib-*.egg
  - echo "y" | pip uninstall winrmlib
  - cd ../..