language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
install:
- pip install -r build_requirements.txt
- pip install -r requirements.txt
script:
- py.test -v --cov winrmlib --cov-report term-missing winrmlib/tests/
after_success:
- pushd .
- coveralls
- pwd && cd src
- python setup.py sdist
- cd ..
- pwd && cd src/dist
- pip install winrmlib-*.tar.gz
- echo "y" | pip uninstall winrmlib
- popd
deploy:
  provider: pypi
  user: iclegg
  distributions: sdist
  password:
    secure: aXmoJxoFmNgMmxATYa86FOkNeJ9TpFD3G5KwE93Qr0fnwcD1ny8XDI4C8nzCgYxDw6j7hEdKqQ+sHnWi/dCoc4bhffzEoziZTTh7qipkPXsjq+lmlR79H+KHDwQtsbrV6N8MdggGsYZYk3pcQ9+cYXqx470D7m8kmaetRxYTGoo=
  on:
    tags: true
    all_branches: true